//
//  SplitViewTestViewController.h
//  Split Test
//
//  Created by Timothy Roe Jr. on 6/11/15.
//  Copyright (c) 2015 Timothy Roe, Jr.
//  THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTAY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NO LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONIFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OR CONTRACT, TORT, OR TOHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


#import <UIKit/UIKit.h>

@interface SplitViewTestViewController : UISplitViewController

@end
